# Generated by Django 2.1.7 on 2019-07-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=8)),
                ('conform_password', models.CharField(max_length=8)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('nationality', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
