# Generated by Django 2.1.7 on 2019-08-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclass',
            name='first_name',
            field=models.CharField(blank=True, default='enter first name', max_length=15),
        ),
        migrations.AlterField(
            model_name='modelclass',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
